# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: 172597598159.dkr.ecr.us-east-1.amazonaws.com/kikeyama-dd-trace-demo-flask-circleci:latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

    working_directory: ~/dd-trace-demo-flask

    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "requirements.txt" }}
#            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-
#
      - run:
          name: docker-build
          command: |
            docker build -t 172597598159.dkr.ecr.us-east-1.amazonaws.com/kikeyama-dd-trace-demo-flask-circleci:latest .

      - run:
          name: docker-tag
          command: |
            docker tag 172597598159.dkr.ecr.us-east-1.amazonaws.com/kikeyama-dd-trace-demo-flask-circleci:latest 172597598159.dkr.ecr.us-east-1.amazonaws.com/kikeyama-dd-trace-demo-flask-circleci:$CIRCLE_BRANCH

      - run:
          name: docker-push-latest
          command: |
            docker push 172597598159.dkr.ecr.us-east-1.amazonaws.com/kikeyama-dd-trace-demo-flask-circleci:latest

      - run:
          name: docker-push-buildtag
          command: |
            docker push 172597598159.dkr.ecr.us-east-1.amazonaws.com/kikeyama-dd-trace-demo-flask-circleci:$CIRCLE_BRANCH

#      - save_cache:
#          paths:
#            - ./venv
#          key: v1-dependencies-{{ checksum "requirements.txt" }}
